apiVersion: v1
kind: Service
metadata:
  name: ww-gitops-weave-gitops-external
  namespace: flux-system
spec:
  selector:
    app: weave-gitops
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

